### ISSUE TITLE
Installation on web

### ISSUE THREAD

**Issue by vertexlex** [cytech/BillingTrack#6]
Tried to install on shared hosting
p 1-7 done
p 8. http://MY_BILLINGTRACK_WEBSITE/setup got 404

**Comment by vertexlex** [comment]
tried    http://MY_BILLINGTRACK_WEBSITE/public/setup 
got:
Database Setup
This step will install and upgrade your database tables. This step may take a few moments to complete.

'Continue' not active

Nothing happened

**Comment by gpfti** [comment]
> Tried to install on shared hosting
> p 1-7 done
> p 8. http://MY_BILLINGTRACK_WEBSITE/setup got 404

I got this "problem" a couple of times in different platform installation (the second installation I forgot how I solved it the first time hahaha). It's not a BillingTrack issue really, but it would help to explain that apache rewrite module must be enable in order to setup work. Laravel needs it.

_In order to use mod_rewrite you can type the following command in the terminal:

sudo a2enmod rewrite
Restart apache2 after

sudo /etc/init.d/apache2 restart__

Have a look to these links:
https://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2
https://laracasts.com/discuss/channels/general-discussion/laravel-5-the-requested-url-was-not-found-on-this-server?page=1

Regards,

Guillermo
